/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.io.File;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.BanDoc;
import models.QLMuonSach;
import models.Sach;

/**
 *
 * @author Quoc Cuong
 */
public class App extends javax.swing.JFrame {

    /**
     * Creates new form App
     */
    private IOFile ioFile;
    private Validation validation;
    private Search search;
    
    public App() {
        initComponents();
        ioFile = new IOFile();
        validation = new Validation();
        search = new Search();
        loadDataToTableSach();
        loadDataToTableBandoc();
        loadDataComboboxInQLMS();
        loadDataToTableQLMS();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        tabTimkiem = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTensach = new javax.swing.JTextField();
        txtTacgia = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jcbChuyennganh = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtNamxb = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSoluong = new javax.swing.JTextField();
        btnThemsach = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblSach = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblSach1 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblSach2 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        btnThemBandoc = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblBandoc = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jcbBanDoc = new javax.swing.JComboBox<>();
        jcbSach = new javax.swing.JComboBox<>();
        txtSoLuongSachMuon = new javax.swing.JTextField();
        btnMuonSach = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblQLMS = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jcbHienTrang = new javax.swing.JComboBox<>();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Tên Sách");

        jLabel2.setText("Tác Giả");

        jLabel3.setText("Chuyên Ngành");

        jcbChuyennganh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Khoa học tự nhiên", "Văn học – Nghệ thuật", "Điện tử Viễn thông", "Công nghệ thông tin" }));

        jLabel4.setText("Năm XB");

        jLabel5.setText("Số Lượng");

        btnThemsach.setText("Thêm");
        btnThemsach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemsachActionPerformed(evt);
            }
        });

        tblSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Sách", "Tên Sách", "Tác Giả", "Chuyên Ngành", "Năm XB", "Số Lượng"
            }
        ));
        jScrollPane3.setViewportView(tblSach);

        tblSach1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã Sách", "Tên Sách", "Tác Giả", "Chuyên Ngành", "Năm XB", "Số Lượng"
            }
        ));
        jScrollPane4.setViewportView(tblSach1);

        tblSach2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã Sách", "Tên Sách", "Tác Giả", "Chuyên Ngành", "Năm XB", "Số Lượng"
            }
        ));
        jScrollPane5.setViewportView(tblSach2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcbChuyennganh, 0, 225, Short.MAX_VALUE)
                            .addComponent(txtNamxb)
                            .addComponent(txtSoluong)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTensach, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                            .addComponent(txtTacgia))))
                .addGap(219, 219, 219))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(291, 291, 291)
                .addComponent(btnThemsach)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(txtTensach))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTacgia, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbChuyennganh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNamxb, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnThemsach)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tabTimkiem.addTab("Thêm Sách", jPanel1);

        jLabel6.setText("Họ tên");

        jLabel7.setText("Địa chỉ");

        jLabel8.setText("SĐT");

        txtDiaChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiaChiActionPerformed(evt);
            }
        });

        txtSDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSDTActionPerformed(evt);
            }
        });

        btnThemBandoc.setText("Thêm");
        btnThemBandoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemBandocActionPerformed(evt);
            }
        });

        tblBandoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Bạn Đọc", "Họ Tên", "Địa Chỉ", "Số ĐT"
            }
        ));
        jScrollPane6.setViewportView(tblBandoc);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(68, 68, 68)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtHoTen)
                            .addComponent(txtDiaChi)
                            .addComponent(txtSDT, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(btnThemBandoc, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(189, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addComponent(btnThemBandoc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(904, Short.MAX_VALUE))
        );

        tabTimkiem.addTab("Thêm Bạn Đọc", jPanel2);

        jLabel9.setText("Bạn đọc");

        jLabel10.setText("Sách");

        jLabel11.setText("Số lượng");

        jcbBanDoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jcbSach.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnMuonSach.setText("Mượn Sách");
        btnMuonSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMuonSachActionPerformed(evt);
            }
        });

        tblQLMS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bạn đọc", "Sách", "Số lượng", "Hien Trang"
            }
        ));
        jScrollPane7.setViewportView(tblQLMS);

        jLabel12.setText("Hien Trang");

        jcbHienTrang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tot", "Khong Tot" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(btnMuonSach, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcbHienTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jcbBanDoc, 0, 212, Short.MAX_VALUE)
                                        .addComponent(jcbSach, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtSoLuongSachMuon)))))))
                .addContainerGap(189, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbBanDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbSach, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoLuongSachMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbHienTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btnMuonSach, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(954, Short.MAX_VALUE))
        );

        tabTimkiem.addTab("QLMuonSach", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabTimkiem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabTimkiem)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemsachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemsachActionPerformed
        // TODO add your handling code here:
        String tenSach = txtTensach.getText();
        String tacGia = txtTacgia.getText();
        String chuyenNganh = jcbChuyennganh.getSelectedItem().toString();
        String namXb = txtNamxb.getText();
        String soLuong = txtSoluong.getText();
        if(validation.isValidThemSach(tenSach, tacGia, namXb, soLuong)){
            int maSach = getMaxMaSach();
            Sach sach = new Sach(maSach, tenSach, tacGia, chuyenNganh, Integer.parseInt(namXb), Integer.parseInt(soLuong));
            ioFile.ghiObjectToFile(sach, "SACH.TXT");
            loadDataToTableSach();
            JOptionPane.showMessageDialog(rootPane, "Them sach thanh cong");
            resetThemSach();
        }
        else{
            String massage = validation.getMassageErrorThemSach(tenSach, tacGia, namXb, soLuong);
            JOptionPane.showMessageDialog(rootPane, massage);
        }
    }//GEN-LAST:event_btnThemsachActionPerformed

    private void txtSDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSDTActionPerformed

    private void txtDiaChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiaChiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiaChiActionPerformed

    private void btnThemBandocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemBandocActionPerformed
        // TODO add your handling code here:
        String hoTen = txtHoTen.getText();
        String diaChi = txtDiaChi.getText();
        String soDT = txtSDT.getText();
        if(validation.isValidThemBanDoc(hoTen, diaChi, soDT)){
            int maBandoc = getMaxMaBanDoc();
            BanDoc banDoc = new BanDoc(maBandoc, hoTen, diaChi, soDT);
            ioFile.ghiObjectToFile(banDoc, "BD.TXT");
            loadDataToTableBandoc();
            JOptionPane.showMessageDialog(rootPane, "Them Ban Doc thanh cong");
            resetThemBanDoc();
        }
        else{
            String massage = validation.getMassageErrorThemBanDoc(hoTen, diaChi, soDT);
            JOptionPane.showMessageDialog(rootPane, massage);
        }
    }//GEN-LAST:event_btnThemBandocActionPerformed

    private void btnMuonSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMuonSachActionPerformed
        // TODO add your handling code here:
        String tenBandoc = jcbBanDoc.getSelectedItem().toString();
        String tenSach = jcbSach.getSelectedItem().toString();
        String soLuongMuonSach = txtSoLuongSachMuon.getText();
        String hienTrang = jcbHienTrang.getSelectedItem().toString();
        ArrayList<QLMuonSach> muonSach = new ArrayList<>();
        if(isFileExists("QLMS.TXT")){
            muonSach = getDataToLoadTableQLMS();
        }
        if(validation.isValidQLMS(muonSach, tenBandoc, tenSach, soLuongMuonSach, hienTrang)){
            QLMuonSach ql = new QLMuonSach(tenBandoc, tenSach, Integer.parseInt(soLuongMuonSach), hienTrang);
            ioFile.ghiObjectToFile(ql, "QLMS.TXT");
            loadDataToTableQLMS();
            JOptionPane.showMessageDialog(rootPane, "Dang ki muon sach thanh cong");
            resetQlMuonSach();
        }
        else{
            String massage = validation.getMassageErrorQLMS(muonSach, tenBandoc, tenSach, soLuongMuonSach,hienTrang);
            JOptionPane.showMessageDialog(rootPane, massage);
        }
    }//GEN-LAST:event_btnMuonSachActionPerformed

    public void resetThemSach(){
        txtTensach.setText("");
        txtTacgia.setText("");
        txtNamxb.setText("");
        txtSoluong.setText("");
    }
    
    public void resetThemBanDoc(){
        txtHoTen.setText("");
        txtDiaChi.setText("");
        txtSDT.setText("");
    }
    
    public void resetQlMuonSach(){
        txtSoLuongSachMuon.setText("");
    }
    
    public int getMaxMaSach(){
        int maxIndex = 9999;
        ArrayList<Sach> listSach = new ArrayList<>();
        if(isFileExists("SACH.TXT")){
            listSach = ioFile.docFileByObject("SACH.TXT");
            if(listSach.size() > 0){
                maxIndex = listSach.get(listSach.size()-1).getMaSach();
            }
        }
        return maxIndex + 1;
    }
    
    public int getMaxMaBanDoc(){
        int maxIndex = 9999;
        ArrayList<BanDoc> listBandoc = new ArrayList<>();
        if(isFileExists("BD.TXT")){
            listBandoc = ioFile.docFileByObject("BD.TXT");
            if(listBandoc.size() > 0){
                maxIndex = listBandoc.get(listBandoc.size()-1).getMaBandoc();
            }
        }
        return maxIndex + 1;
    }
    
    public void loadDataToTableSach(){
        DefaultTableModel model = new DefaultTableModel();
        model = (DefaultTableModel) tblSach.getModel();
        model.getDataVector().removeAllElements();
        ArrayList<Sach> listSach = new ArrayList<>();
        if(this.isFileExists("SACH.TXT")){
            listSach = ioFile.docFileByObject("SACH.TXT");
        }
        for(Sach sach : listSach){
            model.addRow(new Object[]{sach.getMaSach(), sach.getTenSach(), sach.getTacGia(), sach.getChuyenNganh(), sach.getNamXb(), sach.getSoLuong()});
        }
        tblSach.setModel(model);
    }
    
    public void loadDataToTableBandoc(){
        DefaultTableModel model = new DefaultTableModel();
        model = (DefaultTableModel) tblBandoc.getModel();
        model.getDataVector().removeAllElements();
        ArrayList<BanDoc> listBandoc = new ArrayList<>();
        if(isFileExists("BD.TXT")){
            listBandoc = ioFile.docFileByObject("BD.TXT");
        }
        for(BanDoc bandoc : listBandoc){
            model.addRow(new Object[]{bandoc.getMaBandoc(), bandoc.getHoTen(), bandoc.getDiaChi(), bandoc.getSoDT()});
        }
        tblBandoc.setModel(model);
    }
    
    public ArrayList<QLMuonSach> getDataToLoadTableQLMS(){
        ArrayList<QLMuonSach> muonSach = new ArrayList<>();
        if(isFileExists("QLMS.TXT")){
            muonSach = ioFile.docFileByObject("QLMS.TXT");
        }
        ArrayList<QLMuonSach> dataToDisplay = new ArrayList<>();
        for(QLMuonSach ms : muonSach){
            if(search.searchBanDocInQLMS(dataToDisplay, ms.getTenBandoc(), ms.getTenSach()) >= 0){
                int index = search.searchBanDocInQLMS(dataToDisplay, ms.getTenBandoc(), ms.getTenSach());
                int oldQuantity = dataToDisplay.get(index).getSoLuong();
                int newQuantity = oldQuantity + ms.getSoLuong();
                dataToDisplay.get(index).setSoLuong(newQuantity);
            }
            else{
                dataToDisplay.add(ms);
            }
        }
        return dataToDisplay;
    }
    
    public void loadDataToTableQLMS(){
        DefaultTableModel model = new DefaultTableModel();
        model = (DefaultTableModel) tblQLMS.getModel();
        model.getDataVector().removeAllElements();
        ArrayList<QLMuonSach> listQL = getDataToLoadTableQLMS();
        for(QLMuonSach ms : listQL){
            model.addRow(new Object[]{ms.getTenBandoc(), ms.getTenSach(), ms.getSoLuong(), ms.getHienTrang()});
        }
        tblQLMS.setModel(model);
    }
    
    public boolean isFileExists(String name){
        File file = new File(name);
        if(file.isFile()){
            return true;
        }
        return false;
    }
    
    public void loadDataComboboxInQLMS(){
        jcbBanDoc.removeAllItems();
        jcbSach.removeAllItems();
        if(isFileExists("SACH.TXT")){
            ArrayList<Sach> listSach = new ArrayList<>();
            listSach = ioFile.docFileByObject("SACH.TXT");
            for(Sach sach : listSach){
                jcbSach.addItem(sach.getTenSach());
            }
        }
        if(isFileExists("BD.TXT")){
            ArrayList<BanDoc> listbanDoc = new ArrayList<>();
            listbanDoc = ioFile.docFileByObject("BD.TXT");
            for(BanDoc banDoc : listbanDoc){
                jcbBanDoc.addItem(banDoc.getHoTen());
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMuonSach;
    private javax.swing.JButton btnThemBandoc;
    private javax.swing.JButton btnThemsach;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JComboBox<String> jcbBanDoc;
    private javax.swing.JComboBox<String> jcbChuyennganh;
    private javax.swing.JComboBox<String> jcbHienTrang;
    private javax.swing.JComboBox<String> jcbSach;
    private javax.swing.JTabbedPane tabTimkiem;
    private javax.swing.JTable tblBandoc;
    private javax.swing.JTable tblQLMS;
    private javax.swing.JTable tblSach;
    private javax.swing.JTable tblSach1;
    private javax.swing.JTable tblSach2;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtNamxb;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtSoLuongSachMuon;
    private javax.swing.JTextField txtSoluong;
    private javax.swing.JTextField txtTacgia;
    private javax.swing.JTextField txtTensach;
    // End of variables declaration//GEN-END:variables
}
